name: Haskell CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: cachix/install-nix-action@v11
        with:
          skip_adding_nixpkgs_channel: true
      - uses: cachix/cachix-action@v6
        with:
          name: dconf2nix
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: nix-shell --run "nix-build-uncached default.nix" ci.nix
