name: Haskell CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v22

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v12
        with:
          name: dconf2nix
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - run: nix-shell --run "nix-build-uncached default.nix" nix/ci.nix
